name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Backend image
      run: |
        cd backend
        docker build -f Dockerfile.prod -t shahzad18/tutoriam-backend:latest .
        docker push shahzad18/tutoriam-backend:latest

    - name: Build and push Frontend image
      run: |
        cd frontend
        docker build -f Dockerfile.prod -t shahzad18/tutoriam-frontend:latest .
        docker push shahzad18/tutoriam-frontend:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/tutoriam
          docker-compose -f docker-compose.prod.yaml pull
          docker-compose -f docker-compose.prod.yaml down
          docker-compose -f docker-compose.prod.yaml up -d
